// automatically generated by the FlatBuffers compiler, do not modify

package Schema;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Auth extends Table {
  public static Auth getRootAsAuth(ByteBuffer _bb) { return getRootAsAuth(_bb, new Auth()); }
  public static Auth getRootAsAuth(ByteBuffer _bb, Auth obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public Auth __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public boolean verified() { int o = __offset(4); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }

  public static int createAuth(FlatBufferBuilder builder,
      boolean verified) {
    builder.startObject(1);
    Auth.addVerified(builder, verified);
    return Auth.endAuth(builder);
  }

  public static void startAuth(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addVerified(FlatBufferBuilder builder, boolean verified) { builder.addBoolean(0, verified, false); }
  public static int endAuth(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

