// automatically generated by the FlatBuffers compiler, do not modify

package Schema;

public final class Data {
  private Data() { }
  public static final byte NONE = 0;
  public static final byte Chat = 1;
  public static final byte Credentials = 2;
  public static final byte Auth = 3;
  public static final byte Lobbies = 4;

  public static final String[] names = { "NONE", "Chat", "Credentials", "Auth", "Lobbies", };

  public static String name(int e) { return names[e]; }
}

