// automatically generated by the FlatBuffers compiler, do not modify

package Schema;

public final class GameType {
  private GameType() { }
  public static final byte RPS = 0;
  public static final byte COUP = 1;

  public static final String[] names = { "RPS", "COUP", };

  public static String name(int e) { return names[e]; }
}

