// automatically generated by the FlatBuffers compiler, do not modify

package Schema;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class GameUpdate extends Table {
  public static GameUpdate getRootAsGameUpdate(ByteBuffer _bb) { return getRootAsGameUpdate(_bb, new GameUpdate()); }
  public static GameUpdate getRootAsGameUpdate(ByteBuffer _bb, GameUpdate obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public GameUpdate __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte update(int j) { int o = __offset(4); return o != 0 ? bb.get(__vector(o) + j * 1) : 0; }
  public int updateLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }
  public ByteBuffer updateAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }

  public static int createGameUpdate(FlatBufferBuilder builder,
      int updateOffset) {
    builder.startObject(1);
    GameUpdate.addUpdate(builder, updateOffset);
    return GameUpdate.endGameUpdate(builder);
  }

  public static void startGameUpdate(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addUpdate(FlatBufferBuilder builder, int updateOffset) { builder.addOffset(0, updateOffset, 0); }
  public static int createUpdateVector(FlatBufferBuilder builder, byte[] data) { builder.startVector(1, data.length, 1); for (int i = data.length - 1; i >= 0; i--) builder.addByte(data[i]); return builder.endVector(); }
  public static void startUpdateVector(FlatBufferBuilder builder, int numElems) { builder.startVector(1, numElems, 1); }
  public static int endGameUpdate(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

