// automatically generated by the FlatBuffers compiler, do not modify

package Schema;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Lobbies extends Table {
  public static Lobbies getRootAsLobbies(ByteBuffer _bb) { return getRootAsLobbies(_bb, new Lobbies()); }
  public static Lobbies getRootAsLobbies(ByteBuffer _bb, Lobbies obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public Lobbies __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String list(int j) { int o = __offset(4); return o != 0 ? __string(__vector(o) + j * 4) : null; }
  public int listLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }

  public static int createLobbies(FlatBufferBuilder builder,
      int listOffset) {
    builder.startObject(1);
    Lobbies.addList(builder, listOffset);
    return Lobbies.endLobbies(builder);
  }

  public static void startLobbies(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addList(FlatBufferBuilder builder, int listOffset) { builder.addOffset(0, listOffset, 0); }
  public static int createListVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startListVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endLobbies(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

