// automatically generated by the FlatBuffers compiler, do not modify

package Schema;

public final class RequestType {
  private RequestType() { }
  public static final byte CHAT_LOBBIES = 0;
  public static final byte CURRENT_CHAT_LOBBY_INFO = 1;
  public static final byte GAME_LOBBIES = 2;
  public static final byte START_GAME = 3;
  public static final byte LEAVE_GAME = 4;

  public static final String[] names = { "CHAT_LOBBIES", "CURRENT_CHAT_LOBBY_INFO", "GAME_LOBBIES", "START_GAME", "LEAVE_GAME", };

  public static String name(int e) { return names[e]; }
}

